In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.12810764 -0.23506468  1.12252358  0.81039287  0.96193479]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.12810764 -0.23506468  1.12252358  0.81039287  0.96193479]


In [5]:
print(np.dot(a, a.T))

2.9137813095915


In [6]:
a = np.random.randn(5, 1)
print(a)

[[ 0.80078002]
 [ 1.08105741]
 [-1.10703902]
 [-1.26409133]
 [-1.17052285]]


In [7]:
print(a.T)

[[ 0.80078002  1.08105741 -1.10703902 -1.26409133 -1.17052285]]


In [8]:
print(np.dot(a, a.T))

[[ 0.64124864  0.86568917 -0.88649472 -1.01225908 -0.93733131]
 [ 0.86568917  1.16868513 -1.19677273 -1.3665553  -1.26540241]
 [-0.88649472 -1.19677273  1.22553539  1.39939842  1.29581447]
 [-1.01225908 -1.3665553   1.39939842  1.59792689  1.47964779]
 [-0.93733131 -1.26540241  1.29581447  1.47964779  1.37012375]]
